apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inadyn.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "inadyn.configLabels" . | nindent 4 }}
data:
  inadyn.conf: |
    {{ .Values.config | nindent 4 }}
