{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inadyn.fullname" . }}
  labels:
      {{- include "inadyn.configLabels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: "{{ tpl $value $ }}"
  {{- end }}
{{- end }}