repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
      - id: helm-docs-container
        args:
          # Make the tool search for charts only under the `example-charts` directory
          - --chart-search-root=example-charts

ci:
  autofix_commit_msg: "docs: Generate README.md"
